name: Makefile CI

on:
  push:
    branches: [ "i190611" ]
  pull_request:
    branches: [ "i190611" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test
